name: approve

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Setting an environment variable with the value of a configuration variable
  aaa: ${{ vars.SPECIFIC_APPROVERS }}
    
jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Check for Specific Approver
      run: |
        # List of specific approvers to check

        echo "${{ vars.SPECIFIC_APPROVERS }}"
        echo "$aaa"
